import numpy as np
arr=np.array([2,1.1,3,787],dtype="i")
print("DAta type is",arr.dtype)
print(arr)
arr1=np.array(["shan","ali","osama"],)
print(arr1.dtype)
a=np.array([2,4,6,7],dtype=np.int8)
print(a.dtype)
b=np.array([1,8,9],dtype="f")
print(b.dtype)
c=np.array([2,7,9])
new=np.float32(c)
new_one=np.int16(new)
print(new.dtype)
print(c.dtype)
print(new_one.dtype)
print(new)

# arr2=np.array(["c","h","w",4,7])
# print(arr2.dtype)
# ar=[[23,98,987],[78,89,78],[89,67,56]]
# arr3=np.array(ar,dtype=np.float64)
# print(arr3)
# print(arr3.dtype)
# ari=np.float64(arr3)
# print(ari.dtype)
# print(ari)
# aar=np.int_(ari)
# print(aar.dtype)
# arr4=np.array([56,97,98],dtype="f")
# print(arr4)
# print(arr4.dtype)
# zee=arr4.astype(int)
# print(zee)
# zees=np.int_([2,4,5,7])
# print(zees)